WorkMaze/JUST.net

- Examples/Transformer_valueofarray.json
- JUST.net/DataTransformer.cs
- JUST.net/JsonTransformer.cs
- JUST.net/ReflectionHelper.cs
- JUST.net/Transformer.cs
- README.md
Issue #46 
Allow multiple elements' filter on "#valueof" function, by including an optional boolean parameter. When set to true will return an array, empty if none element is found.
> Filtering arrays with "#valueof" multiple tokens

- Examples/Transformer_valueofarray.json
- JUST.net/DataTransformer.cs
- JUST.net/JsonTransformer.cs
- JUST.net/ReflectionHelper.cs
- JUST.net/Transformer.cs
- README.md
> Revert "Filtering arrays with "#valueof" multiple tokens"

- JUST.net/JUST.net.csproj
- JUST.net/JUSTContext.cs
- JUST.net/JsonTransformer.cs
- Program.cs
- README.md
JUSTContext is now a non-static class that can be passed to Transform methods. Function's registration works the same as before.
JsonTransformer as a global JUSTContext, called "GlobalContext", that works for all calls of Transform methods.
> Non static JUSTContext

- JUST.net/JsonTransformer.cs
#47 
Only evaluate expression according to ifcondition comparison result
> Ifcondition evaluation

- JUST.net/Transformer.cs
- UnitTests/ValueOfTests.cs
> Double precision

- JUST.net/JsonTransformer.cs
- README.md
- UnitTests/ApplyOverTests.cs
- UnitTests/ReadmeTests.cs
Based on #66 
A solution could not be achieved with only one transformation, so it would be handy to be able to apply another "transformation"/function over an already transformed result.
> Applyover function

- JUST.net/JsonTransformer.cs
- UnitTests/ConditionalFunctionsTests.cs
> ifgroup loop fix

- JUST.net/JsonTransformer.cs
- UnitTests/Arrays/LoopingTests.cs
> Empty array loop returns empty array

- JUST.net/JsonTransformer.cs
I just added the if condition to check whether arrayToken != null. This seemed to work.
> Fixed issue 116

- JUST.net/JsonTransformer.cs
- UnitTests/ConditionalFunctionsTests.cs
- UnitTests/LoadTests.cs
- UnitTests/ReadmeTests.cs
> Fix issue104

- JUST.net/ComparisonHelper.cs
- JUST.net/JsonTransformer.cs
- JUST.net/Transformer.cs
- UnitTests/ApplyOverTests.cs
- UnitTests/ConditionalFunctionsTests.cs
- UnitTests/ReadmeTests.cs
- UnitTests/StringFunctionsTests.cs
> fixed exception on funcs targeting a null node

- JUST.net/JsonTransformer.cs
- UnitTests/Arrays/LoopingTests.cs
#146 
Only the last loop under a property would "survive", the other ones were lost.
With this fix, one can have multiple loops under the same property, it results in a single array with all the elements.
> Loops for the same property

- JUST.net/JsonTransformer.cs
- UnitTests/Arrays/LoopingTests.cs
- azure-pipelines.yml
> Loop over properties loses previous alias

- JUST.net/JsonTransformer.cs
- UnitTests/Arrays/LoopingTests.cs
- azure-pipelines.yml
> Fix adding a null value to array

- JUST.net/Transformer.cs
- README.md
- UnitTests/ReadmeTests.cs
- UnitTests/TypeCheckTests.cs
- UnitTests/TypeConversionTests.cs
Check if a value is a number (#isnumber), boolean (#isboolean), string (#isstring) or array (#isarray).
#isnumber will return true for both integer and decimals, do to implicit convertion in .Net
#113
> Functions to check types

- JUST.net/JsonTransformer.cs
- UnitTests/ArrayInputTests.cs
Fix loop when root element is an array
#171
> First element fix when root array looping

- .gitignore
- JUST.net/JUST.net.csproj
- UnitTests/JUST.net.UnitTests.csproj
Update Newtonsoft Json, NJsonSchema and JmesPath packages;
JUST.net project with .Net Frameworks 4.5 only, it works with every framework beyond that
Unit Tests project sdk to dotnet core 3.1
> Update SDK and packages

- JUST.net/DataTransformer.cs
- JUST.net/ExpressionHelper.cs
- JUST.net/JUSTContext.cs
- JUST.net/JsonTransformer.cs
- README.md
- UnitTests/ArgumentsEscapeTests.cs
Abitily to choose the escape char
#186
> Choose escape char

- JUST.net/JsonTransformer.cs
- JUST.net/Transformer.cs
- README.md
- UnitTests/ConditionalFunctionsTests.cs
- UnitTests/ReadmeTests.cs
Now is possible to include or exclude a value in an array based on a condition.
> Function ifgroup can also be used to evaluate a single value

- JUST.net/JsonTransformer.cs
- UnitTests/DynamicPropertiesTests.cs
Fix bug when passing an object as value of #eval
#193
> #eval with object as value

- JUST.net/JsonTransformer.cs
This fixes compile, it was not working
> Fix compile

- JUST.net/Transformer.cs
- README.md
- UnitTests/ConditionalFunctionsTests.cs
- UnitTests/ReadmeTests.cs
#arrayempty function to represent empty array
#204
> Add function to represent empty array

- JUST.net/JUSTContext.cs
- JUST.net/Transformer.cs
- README.md
- UnitTests/Arrays/GroupFunctionsTests.cs
> Possibility to redefine split group character

- JUST.net/JsonTransformer.cs
> Rename generic to prevent warnings

- JUST.net/DataTransformer.cs
> Fix infinite loop in DataTransformer when value is empty

- README.md
Formatting issue with READme.md file in the output json section
#285
> #285 Formatting issue with READme.md file in the output json section
